//! Book signals: a content fingerprint plus quality signals, computed once on
//! first import and cached in `data/book-signals.json` keyed by file revision.
//!
//! Purpose (product decided): detect duplicate editions already in the shelf
//! (hint only, never auto-merge) and grade each book 优/良/中 for shelf
//! ordering and the cover badge. Everything is deterministic, local and
//! explainable — no AI, no per-list recomputation.

use std::collections::HashMap;
use std::fs;

use iced_reader_core::Book;
use serde::{Deserialize, Serialize};

use crate::portable;

/// How trustworthy the epub's own identifier is (best first).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum IdQuality {
    /// ISBN-like (978/979 or a bare ISBN), usually links to the printed book.
    Isbn,
    /// Store-ish alphanumeric id (Amazon ASIN etc.).
    Asin,
    /// A stable non-random id of unknown shape.
    Other,
    /// Random UUID — regenerated by most repacking tools.
    RandomUuid,
    /// No identifier at all.
    None,
}

impl IdQuality {
    pub fn rank(self) -> u8 {
        match self {
            IdQuality::Isbn => 3,
            IdQuality::Asin => 2,
            IdQuality::Other => 1,
            IdQuality::RandomUuid | IdQuality::None => 0,
        }
    }
}

/// Classify one identifier string. ISBN wins, ASIN (10-char alnum incl. at
/// least one letter) next, bare uuids are treated as repack noise.
pub fn classify_identifier(id: &str) -> IdQuality {
    let t = id.trim();
    if t.is_empty() {
        return IdQuality::None;
    }
    let lower = t.to_ascii_lowercase();
    let digits: String = t.chars().filter(|c| c.is_ascii_digit()).collect();
    if lower.starts_with("urn:isbn")
        || lower.starts_with("isbn:")
        || t.starts_with("978")
        || t.starts_with("979")
        || (digits.len() >= 10 && digits.len() <= 13 && t.len() <= 20)
    {
        return IdQuality::Isbn;
    }
    if lower.starts_with("urn:uuid") || is_uuid(t) {
        return IdQuality::RandomUuid;
    }
    let alnum: String = t.chars().filter(|c| c.is_ascii_alphanumeric()).collect();
    if alnum.len() == 10 && t.len() <= 16 && alnum.chars().any(|c| c.is_ascii_alphabetic()) {
        return IdQuality::Asin;
    }
    IdQuality::Other
}

fn is_uuid(s: &str) -> bool {
    let s = s.trim();
    s.len() == 36
        && s.bytes().enumerate().all(|(i, b)| match b {
            b'-' => matches!(i, 8 | 13 | 18 | 23),
            _ => b.is_ascii_hexdigit(),
        })
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BookSignals {
    /// File revision this signal set was computed for (len+mtime).
    pub rev: String,
    /// Total visible characters (whitespace removed) of the spine documents.
    pub chars: u64,
    /// Per-document text sha256 (first 16 hex) in spine order. Equal sequences
    /// ⇒ the very same typesetting, even if repacked/renamed.
    pub chapter_shas: Vec<String>,
    /// sha of the joined `chapter_shas` — cheap group key.
    pub fingerprint: String,
    /// Replacement character count (mojibake) across the spine text.
    pub mojibake: u64,
    /// `<br` occurrences (hard line breaks) across spine documents.
    pub br_count: u64,
    /// Empty paragraphs.
    pub empty_p: u64,
    /// `<img` occurrences inside spine documents.
    pub img_count: u64,
    /// First heading text of each spine document (empty when none).
    pub headings: Vec<String>,
    pub id_quality: IdQuality,
    pub has_creator: bool,
    /// Whole-archive image files / decoded bytes (bounded scan; truncated flag
    /// means the scan stopped early because the book is image-heavy).
    pub img_files: u64,
    pub img_bytes: u64,
    pub img_truncated: bool,
}

/// Collection-time raw stats of one spine document.
struct Scan {
    text: String,
    mojibake: u64,
    br: u64,
    empty_p: u64,
    imgs: u64,
    headings: Vec<String>,
}

fn decode_entities(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let bytes = s.as_bytes();
    let mut i = 0usize;
    while i < bytes.len() {
        if bytes[i] != b'&' {
            let ch = s[i..].chars().next().unwrap();
            out.push(ch);
            i += ch.len_utf8();
            continue;
        }
        let tail = &s[i..];
        let mut replaced = false;
        for (ent, rep) in [
            ("&amp;", "&"),
            ("&lt;", "<"),
            ("&gt;", ">"),
            ("&quot;", "\""),
            ("&apos;", "'"),
            ("&#39;", "'"),
            ("&nbsp;", " "),
        ] {
            if tail.starts_with(ent) {
                out.push_str(rep);
                i += ent.len();
                replaced = true;
                break;
            }
        }
        if replaced {
            continue;
        }
        // numeric: &#123; / &#x1f;
        if let Some(semi) = tail.find(';') {
            let cand = &tail[..semi];
            if let Some(rest) = cand.strip_prefix("&#") {
                let parsed = match rest.strip_prefix(['x', 'X']) {
                    Some(hexpart) => u32::from_str_radix(hexpart, 16),
                    None => rest.parse::<u32>(),
                };
                if let Ok(cp) = parsed {
                    if let Some(c) = char::from_u32(cp) {
                        if c != '\0' {
                            out.push(c);
                            i += semi + 1;
                            continue;
                        }
                    }
                }
            }
        }
        out.push('&');
        i += 1;
    }
    out
}

/// Lightweight HTML→visible-text scan. UTF-8 safe; handles comments,
/// script/style skipping, tags, headings (h1–h6), `<p>` emptiness, `<br>`,
/// `<img>` counting and mojibake counting. This is fingerprint text, not a
/// render — entity decoding is best-effort.
fn scan_html(raw: &str) -> Scan {
    let mut text = String::new();
    let mut mojibake = 0u64;
    let mut br = 0u64;
    let mut empty_p = 0u64;
    let mut imgs = 0u64;
    let mut headings: Vec<String> = Vec::new();

    let chars: Vec<char> = raw.chars().collect();
    let n = chars.len();
    let mut i = 0usize;
    let mut in_comment = false;
    let mut skip_until = None::<String>; // e.g. "/script" while inside script/style
    let mut p_depth = 0usize;
    let mut p_text_flags: Vec<bool> = Vec::new(); // per open <p>
    let mut heading: Option<String> = None; // current heading element name (lowercase)
    let mut heading_buf = String::new();
    let mut saw_visible = false;

    while i < n {
        let c = chars[i];
        if in_comment {
            if c == '-' && i + 2 < n && chars[i + 1] == '-' && chars[i + 2] == '>' {
                in_comment = false;
                i += 3;
            } else {
                i += 1;
            }
            continue;
        }
        if let Some(name) = skip_until.as_deref() {
            // inside <script>/<style>: find the closing tag (match on the char
            // array — byte slices do not line up once CJK text is present)
            if c == '<' && i + 1 < n && chars[i + 1] == '/' {
                let mut k = i + 2;
                let mut matches = true;
                for nc in name.chars() {
                    if k < n && chars[k] == nc {
                        k += 1;
                    } else {
                        matches = false;
                        break;
                    }
                }
                if matches {
                    // consume the whole closing tag
                    while i < n && chars[i] != '>' {
                        i += 1;
                    }
                    if i < n {
                        i += 1;
                    }
                    skip_until = None;
                    continue;
                }
            }
            i += 1;
            continue;
        }
        if c == '<' {
            // find tag name
            let mut j = i + 1;
            if j < n && chars[j] == '!' {
                if j + 1 < n && chars[j + 1] == '-' && j + 2 < n && chars[j + 2] == '-' {
                    in_comment = true;
                    i = j + 3;
                    continue;
                }
                // other declarations (<!doctype …>): skip to '>'
                while i < n && chars[i] != '>' {
                    i += 1;
                }
                if i < n {
                    i += 1;
                }
                continue;
            }
            let mut name = String::new();
            if j < n && chars[j] == '/' {
                name.push('/');
                j += 1;
            }
            while j < n && (chars[j].is_ascii_alphanumeric()) {
                name.push(chars[j].to_ascii_lowercase());
                j += 1;
            }

            match name.as_str() {
                "" => {
                    // stray '<'
                    text.push('<');
                    i += 1;
                    continue;
                }
                "script" | "style" => {
                    skip_until = Some(name.clone());
                    i = j; // tag body will be skipped by the '>' walk below
                    // consume tag until '>'
                    while i < n && chars[i] != '>' {
                        i += 1;
                    }
                    if i < n {
                        i += 1;
                    }
                    continue;
                }
                "br" => {
                    br += 1;
                    // consume rest of tag
                    while i < n && chars[i] != '>' {
                        i += 1;
                    }
                    if i < n {
                        i += 1;
                    }
                    continue;
                }
                "img" => {
                    imgs += 1;
                    while i < n && chars[i] != '>' {
                        i += 1;
                    }
                    if i < n {
                        i += 1;
                    }
                    continue;
                }
                "p" => {
                    p_depth += 1;
                    p_text_flags.push(false);
                    heading = None;
                    while i < n && chars[i] != '>' {
                        i += 1;
                    }
                    if i < n {
                        i += 1;
                    }
                    continue;
                }
                "/p" => {
                    if p_depth > 0 {
                        p_depth -= 1;
                        if let Some(flag) = p_text_flags.pop() {
                            if !flag {
                                empty_p += 1;
                            }
                        }
                    }
                    heading = None;
                    while i < n && chars[i] != '>' {
                        i += 1;
                    }
                    if i < n {
                        i += 1;
                    }
                    continue;
                }
                h if h.len() == 2 && h.starts_with('h') && matches!(h.as_bytes()[1], b'1'..=b'6') =>
                {
                    heading = Some(h.to_string());
                    heading_buf.clear();
                    while i < n && chars[i] != '>' {
                        i += 1;
                    }
                    if i < n {
                        i += 1;
                    }
                    continue;
                }
                h if h.starts_with("/h")
                    && h.len() == 3
                    && matches!(h.as_bytes()[2], b'1'..=b'6') =>
                {
                    if heading.is_some() {
                        let t = heading_buf.trim().to_string();
                        headings.push(t);
                    }
                    heading = None;
                    heading_buf.clear();
                    while i < n && chars[i] != '>' {
                        i += 1;
                    }
                    if i < n {
                        i += 1;
                    }
                    continue;
                }
                _ => {
                    // any other tag: skip to '>'
                    while i < n && chars[i] != '>' {
                        i += 1;
                    }
                    if i < n {
                        i += 1;
                    }
                    continue;
                }
            }
        }
        // visible text
        if heading.is_some() {
            heading_buf.push(c);
        }
        text.push(c);
        if c == '\u{FFFD}' {
            mojibake += 1;
        }
        if !c.is_whitespace() {
            saw_visible = true;
            if p_depth > 0 {
                if let Some(f) = p_text_flags.last_mut() {
                    *f = true;
                }
            }
        }
        i += 1;
    }
    let _ = saw_visible;
    Scan {
        text: text.trim().to_string(),
        mojibake,
        br,
        empty_p,
        imgs,
        headings,
    }
}

fn norm_ws(s: &str) -> String {
    s.chars().filter(|c| !c.is_whitespace()).collect()
}

fn sha16(s: &str) -> String {
    use sha2::{Digest, Sha256};
    let mut d = Sha256::new();
    d.update(s.as_bytes());
    let out = d.finalize();
    out[..8].iter().map(|b| format!("{b:02x}")).collect()
}

fn file_of_href(href: &str) -> String {
    href.split(['#', '?']).next().unwrap_or(href).to_string()
}

/// Compute signals for an opened book. `rev` is the file revision used as the
/// cache key. Reading happens through the Book trait (no rendering, no
/// word-note expansion) so first import of a huge book stays bounded.
pub fn analyze_book(
    book: &dyn Book,
    identifiers: &[String],
    has_creator: bool,
    rev: &str,
    images: (usize, u64, bool),
) -> Result<BookSignals, String> {
    let spine = book.spine();
    let id_quality = identifiers
        .iter()
        .map(|s| classify_identifier(s))
        .max_by_key(|q| q.rank())
        .unwrap_or(IdQuality::None);

    let mut shas: Vec<String> = Vec::with_capacity(spine.len());
    let mut chars: u64 = 0;
    let mut mojibake = 0u64;
    let mut br_count = 0u64;
    let mut empty_p = 0u64;
    let mut img_count = 0u64;
    let mut headings: Vec<String> = Vec::new();
    let mut text_cache: HashMap<String, String> = HashMap::new();

    for item in &spine {
        let file = file_of_href(&item.href);
        let text = if let Some(t) = text_cache.get(&file) {
            t.clone()
        } else {
            let res = book
                .resource(&file)
                .map_err(|e| format!("read {file}: {e}"))?;
            let raw = String::from_utf8_lossy(&res.data);
            let scan = scan_html(&raw);
            mojibake += scan.mojibake;
            br_count += scan.br;
            empty_p += scan.empty_p;
            img_count += scan.imgs;
            let decoded = decode_entities(&scan.text);
            let normed = norm_ws(&decoded);
            if let Some(first_heading) = scan.headings.into_iter().next() {
                headings.push(norm_ws(&first_heading));
            } else {
                headings.push(String::new());
            }
            text_cache.insert(file.clone(), normed.clone());
            normed
        };
        chars += text.chars().count() as u64;
        shas.push(sha16(&text));
    }

    let fingerprint = sha16(&shas.join("|"));
    Ok(BookSignals {
        rev: rev.to_string(),
        chars,
        chapter_shas: shas,
        fingerprint,
        mojibake,
        br_count,
        empty_p,
        img_count,
        headings,
        id_quality,
        has_creator,
        img_files: images.0 as u64,
        img_bytes: images.1,
        img_truncated: images.2,
    })
}

/// Grade 优/良/中 with plain-language reasons. Rules are conservative: only
/// facts we measured, no invented criteria.
pub fn grade(s: &BookSignals) -> (&'static str, Vec<String>) {
    let mut reasons: Vec<String> = Vec::new();
    let mut bad = 0u8;
    let mut good = 0u8;

    if s.chars == 0 {
        reasons.push("未读到正文（空书或纯图片书）".into());
        return ("中", reasons);
    }
    reasons.push(format!("正文约 {} 字", s.chars));

    if s.mojibake > 0 {
        bad += 1;
        reasons.push(format!("正文含 {} 处乱码替换符", s.mojibake));
    } else {
        good += 1;
        reasons.push("未发现乱码".into());
    }
    let br_per_k = s.br_count as f64 * 1000.0 / s.chars as f64;
    if br_per_k > 12.0 {
        bad += 1;
        reasons.push(format!("换行符偏多（约 {:.0}/千字），排版较粗糙", br_per_k));
    } else if s.br_count > 0 {
        reasons.push(format!("换行符约 {:.1}/千字", br_per_k));
    }
    if s.img_files > 0 {
        if s.img_truncated {
            reasons.push(format!("插图 {} 张（统计截断）", s.img_files));
        } else {
            reasons.push(format!("插图 {} 张", s.img_files));
        }
        let per_kb = s.img_bytes as f64 / s.img_files as f64 / 1024.0;
        if s.img_truncated {
            // image-heavy book; no clarity claim
        } else if per_kb >= 20.0 {
            good += 1;
            reasons.push(format!("图像码率高（约 {per_kb:.0}KB/张，较清晰）"));
        } else if per_kb > 0.0 {
            reasons.push(format!("图像约 {per_kb:.0}KB/张"));
        }
    }
    match s.id_quality {
        IdQuality::Isbn => {
            good += 2;
            reasons.push("标识符为 ISBN，可溯源纸书版本".into());
        }
        IdQuality::Asin => {
            good += 1;
            reasons.push("标识符为商店编号，可溯源到商店条目".into());
        }
        IdQuality::Other => {
            reasons.push("标识符为自定义编号".into());
        }
        IdQuality::RandomUuid => {
            reasons.push("标识符是随机 UUID，难以据此溯源".into());
        }
        IdQuality::None => {
            reasons.push("无标识符".into());
        }
    }
    if s.has_creator {
        good += 1;
        reasons.push("含作者/整理者信息".into());
    } else {
        reasons.push("缺少作者/整理者信息".into());
    }
    if s.headings.iter().filter(|h| !h.is_empty()).count() == 0 {
        reasons.push("未识别到章节标题结构".into());
    }

    // 优 needs a clean, well-sourced, clearly produced book; 良 tolerates
    // missing provenance; anything with defects (or a bare text) lands on 中.
    let grade = if bad == 0 && good >= 4 {
        "优"
    } else if bad == 0 && good >= 2 {
        "良"
    } else {
        "中"
    };
    (grade, reasons)
}

// ---- persistence: data/book-signals.json (fileName → signals) ----

pub fn read_all() -> HashMap<String, BookSignals> {
    let Ok(path) = portable::signals_file() else {
        return HashMap::new();
    };
    read_from(&path)
}

pub fn read_from(path: &std::path::Path) -> HashMap<String, BookSignals> {
    match fs::read(path) {
        Ok(bytes) => serde_json::from_slice(&bytes).unwrap_or_default(),
        Err(_) => HashMap::new(),
    }
}

pub fn write_one(file_name: &str, signals: &BookSignals) {
    let Ok(path) = portable::signals_file() else {
        return;
    };
    let mut all = read_from(&path);
    all.insert(file_name.to_string(), signals.clone());
    persist(&path, &all);
}

pub fn remove(file_name: &str) {
    let Ok(path) = portable::signals_file() else {
        return;
    };
    let mut all = read_from(&path);
    if all.remove(file_name).is_some() {
        persist(&path, &all);
    }
}

fn persist(path: &std::path::Path, all: &HashMap<String, BookSignals>) {
    if let Some(dir) = path.parent() {
        let _ = fs::create_dir_all(dir);
    }
    let tmp = path.with_extension("json.tmp");
    if let Ok(data) = serde_json::to_vec_pretty(all) {
        if fs::write(&tmp, data).is_ok() {
            let _ = fs::rename(&tmp, path);
        }
    }
}


#[cfg(test)]
mod tests {
    use super::*;
    use iced_reader_epub::EpubOpener;
    use iced_reader_core::BookOpener;

    #[test]
    fn classify_identifiers() {
        assert_eq!(classify_identifier("urn:isbn:9787020058716"), IdQuality::Isbn);
        assert_eq!(classify_identifier("9787020058716"), IdQuality::Isbn);
        assert_eq!(classify_identifier("B00PXVU09M"), IdQuality::Asin);
        assert_eq!(classify_identifier("urn:uuid:fc167612-40a5-4d22-a912-dae048e3e9d1"), IdQuality::RandomUuid);
        assert_eq!(classify_identifier("fc167612-40a5-4d22-a912-dae048e3e9d1"), IdQuality::RandomUuid);
        assert_eq!(classify_identifier("mybook-v1"), IdQuality::Other);
        assert_eq!(classify_identifier(""), IdQuality::None);
    }

    #[test]
    fn scan_extracts_text_and_signal_counts() {
        let raw = r#"<html><body><h1>第一回 周宣王</h1><p>正文文本。</p><p>  </p><script>var x=1;</script><style>p{}</style><img src="a.png"/>行<br/>尾</body></html>"#;
        let s = scan_html(raw);
        assert_eq!(s.headings, vec!["第一回 周宣王".to_string()]);
        assert!(s.text.contains("正文文本。"));
        assert!(!s.text.contains("var x"));
        assert_eq!(s.br, 1);
        assert_eq!(s.empty_p, 1);
        assert_eq!(s.imgs, 1);
        assert_eq!(s.mojibake, 0);
    }

    #[test]
    fn mojibake_and_entity_decoding() {
        let raw = "<p>好\u{FFFD}文 &amp; &#65; &#x42; &lt;x&gt;</p>";
        let scan = scan_html(raw);
        assert_eq!(scan.mojibake, 1);
        let out = decode_entities(&scan.text);
        assert!(out.contains("好\u{FFFD}文 & A B <x>"), "{out}");
    }

    #[test]
    fn analyze_and_grade_sample_epub() {
        let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../fixtures/sample.epub");
        let book = EpubOpener.open(&path).expect("open sample");
        let meta = book.metadata();
        let signals = analyze_book(book.as_ref(), &meta.identifiers, !meta.authors.is_empty(), "r1", (0, 0, false))
            .expect("analyze");
        assert!(signals.chars > 0, "sample has readable text");
        assert!(!signals.chapter_shas.is_empty());
        let (grade, reasons) = grade(&signals);
        assert!(["优", "良", "中"].contains(&grade), "{grade}");
        assert!(!reasons.is_empty());
    }

    #[test]
    fn signals_cache_roundtrip() {
        let dir = std::env::temp_dir().join("icedreader-signals-test");
        let _ = std::fs::create_dir_all(&dir);
        let file = dir.join("signals.json");
        let sig = BookSignals {
            rev: "r1".into(),
            chars: 12,
            chapter_shas: vec!["ab".into()],
            fingerprint: "f".into(),
            mojibake: 0,
            br_count: 1,
            empty_p: 0,
            img_count: 2,
            headings: vec!["第一回".into()],
            id_quality: IdQuality::Isbn,
            has_creator: true,
            img_files: 3,
            img_bytes: 12_000,
            img_truncated: false,
        };
        let mut all = std::collections::HashMap::new();
        all.insert("a.epub".to_string(), sig.clone());
        persist(&file, &all);
        let back = read_from(&file);
        assert_eq!(back.get("a.epub").unwrap().fingerprint, "f");
    }
}

