//! User annotations (highlights) keyed by the same progress key as reading
//! progress (`id:...` / `lib:...`). A highlight anchors to a span inside one
//! chapter by global text-node sequence + in-node offset, stable because
//! chapter HTML is regenerated deterministically on every open.

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use crate::{same_book, CoreError};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Highlight {
    /// Stable id generated by the caller (Tauri layer, uuid v4).
    pub id: String,
    /// Chapter href exactly as the spine uses it (may carry a `#fragment`).
    pub href: String,
    /// Index of the start text node among all text nodes in that chapter doc.
    pub start_text: usize,
    /// Offset inside the start text node.
    pub start_offset: usize,
    /// Index of the end text node (exclusive span end).
    pub end_text: usize,
    /// Offset inside the end text node.
    pub end_offset: usize,
    /// Excerpt of the highlighted plain text (validation + future listings).
    pub text: String,
    /// Decided at stroke time; never edited afterwards (换色 = 删除重划).
    /// Opinionated semantics: yellow = 重点 (default), green = 摘抄.
    #[serde(default = "default_highlight_color")]
    pub color: String,
    /// Whole-book position 0–1 computed by the caller from per-chapter raw
    /// visible-text char weights (same char regime as the front-end text
    /// nodes). Written into notes.md and used by 按位置跳转.
    #[serde(default)]
    pub pos: f64,
    pub created_at: i64,
}

/// Opinionated highlight colours. Yellow = 重点 (broad: any thought —
/// 重点/思考/存疑), green = 摘抄 (pure excerpt). The value is the storage
/// key and the `::highlight(iced-reader-highlight-{color})` suffix.
pub const COLOR_YELLOW: &str = "yellow";
pub const COLOR_GREEN: &str = "green";

fn default_highlight_color() -> String {
    COLOR_YELLOW.to_string()
}

#[derive(Debug, Default)]
pub struct AnnotationStore {
    path: Option<PathBuf>,
    by_book: HashMap<String, Vec<Highlight>>,
}

impl AnnotationStore {
    pub fn in_memory() -> Self {
        Self::default()
    }

    pub fn open(path: PathBuf) -> Result<Self, CoreError> {
        let by_book = if path.exists() {
            let bytes = fs::read(&path).map_err(|e| CoreError::msg(e.to_string()))?;
            serde_json::from_slice(&bytes).unwrap_or_default()
        } else {
            HashMap::new()
        };
        Ok(Self {
            path: Some(path),
            by_book,
        })
    }

    /// Highlights for one book, in insertion order.
    pub fn list(&self, key: &str) -> Vec<Highlight> {
        self.by_book.get(key).cloned().unwrap_or_default()
    }

    /// Insert or replace (same id) one highlight. Order is preserved.
    pub fn add(&mut self, key: String, highlight: Highlight) -> Result<(), CoreError> {
        let list = self.by_book.entry(key).or_default();
        if let Some(slot) = list.iter_mut().find(|h| h.id == highlight.id) {
            *slot = highlight;
        } else {
            list.push(highlight);
        }
        self.persist()
    }

    /// Remove one highlight; returns whether anything was removed.
    pub fn remove(&mut self, key: &str, id: &str) -> Result<bool, CoreError> {
        let Some(list) = self.by_book.get_mut(key) else {
            return Ok(false);
        };
        let before = list.len();
        list.retain(|h| h.id != id);
        let removed = list.len() != before;
        if removed {
            self.persist()?;
        }
        Ok(removed)
    }

    /// Re-key one book's highlights after its file was renamed in the
    /// library. Only meaningful for `lib:` keys (they embed the file name);
    /// callers skip `id:`/`path:` keys. All keys aliasing `old` (numbered
    /// copies share a stem) merge into `new`, insertion order preserved.
    pub fn rename_book(&mut self, old: &str, new: &str) -> Result<(), CoreError> {
        if old == new {
            return Ok(());
        }
        // Only `lib:` keys embed the file name; `id:`/`path:` keys survive a
        // rename untouched and must never be rewritten here.
        if !(old.starts_with("lib:") && new.starts_with("lib:")) {
            return Ok(());
        }
        let affected: Vec<String> = self
            .by_book
            .keys()
            .filter(|k| same_book(k, old))
            .cloned()
            .collect();
        if affected.is_empty() {
            return Ok(());
        }
        let mut merged: Vec<Highlight> = Vec::new();
        // Deterministic order: aliases merge in key order (HashMap iteration
        // order is not stable across runs).
        let mut keys = affected;
        keys.sort();
        for key in keys {
            if let Some(list) = self.by_book.remove(&key) {
                merged.extend(list);
            }
        }
        self.by_book.insert(new.to_string(), merged);
        self.persist()
    }

    /// Remove every record belonging to one book: the exact key plus any
    /// `lib:` stem aliases that the progress key treats as the same book.
    /// Returns whether anything was removed.
    pub fn remove_book(&mut self, key: &str) -> Result<bool, CoreError> {
        if !self.by_book.keys().any(|k| same_book(k, key)) {
            return Ok(false);
        }
        self.by_book.retain(|k, _| !same_book(k, key));
        self.persist()?;
        Ok(true)
    }

    fn persist(&self) -> Result<(), CoreError> {
        let Some(path) = &self.path else {
            return Ok(());
        };
        if let Some(dir) = path.parent() {
            fs::create_dir_all(dir).map_err(|e| CoreError::msg(e.to_string()))?;
        }
        let tmp = path.with_extension("json.tmp");
        let data =
            serde_json::to_vec_pretty(&self.by_book).map_err(|e| CoreError::msg(e.to_string()))?;
        fs::write(&tmp, data).map_err(|e| CoreError::msg(e.to_string()))?;
        fs::rename(&tmp, path).map_err(|e| CoreError::msg(e.to_string()))?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn hl(id: &str, start_text: usize, start_offset: usize) -> Highlight {
        Highlight {
            id: id.into(),
            href: "/EPUB/ch2.xhtml".into(),
            start_text,
            start_offset,
            end_text: start_text,
            end_offset: start_offset + 5,
            text: "示例摘录……".into(),
            color: COLOR_YELLOW.into(),
            pos: 0.25,
            created_at: 100 + start_offset as i64,
        }
    }

    #[test]
    fn roundtrip_file_store() {
        let dir = std::env::temp_dir().join("icedreader-annotations-test");
        let _ = fs::create_dir_all(&dir);
        let path = dir.join("annotations.json");
        let _ = fs::remove_file(&path);

        let mut store = AnnotationStore::open(path.clone()).unwrap();
        store.add("lib:foo.epub".into(), hl("a", 0, 0)).unwrap();
        store.add("lib:foo.epub".into(), hl("b", 3, 7)).unwrap();

        let reloaded = AnnotationStore::open(path).unwrap();
        let list = reloaded.list("lib:foo.epub");
        assert_eq!(list.len(), 2);
        assert_eq!(list[0].id, "a");
        assert_eq!(list[1].start_text, 3);
        assert_eq!(list[1].start_offset, 7);
    }

    #[test]
    fn removes_and_reports_missing() {
        let mut store = AnnotationStore::in_memory();
        store.add("k".into(), hl("a", 1, 0)).unwrap();
        assert!(store.remove("k", "a").unwrap());
        assert!(store.list("k").is_empty());
        assert!(!store.remove("k", "a").unwrap());
        assert!(!store.remove("other", "a").unwrap());
    }

    #[test]
    fn remove_book_clears_book_and_its_lib_aliases() {
        let mut store = AnnotationStore::in_memory();
        store.add("lib:foo.epub".into(), hl("a", 0, 0)).unwrap();
        store.add("lib:foo-2.epub".into(), hl("b", 1, 0)).unwrap();
        store.add("lib:bar.epub".into(), hl("c", 2, 0)).unwrap();
        store.add("id:x".into(), hl("d", 3, 0)).unwrap();

        assert!(store.remove_book("lib:foo.epub").unwrap());
        assert!(store.list("lib:foo.epub").is_empty());
        assert!(store.list("lib:foo-2.epub").is_empty());
        assert_eq!(store.list("lib:bar.epub").len(), 1);
        assert_eq!(store.list("id:x").len(), 1);
        assert!(!store.remove_book("lib:foo.epub").unwrap());
    }

    #[test]
    fn rename_book_moves_aliases_under_new_key() {
        let mut store = AnnotationStore::in_memory();
        store.add("lib:foo.epub".into(), hl("a", 0, 0)).unwrap();
        store.add("lib:foo-2.epub".into(), hl("b", 1, 0)).unwrap();
        store.add("lib:bar.epub".into(), hl("c", 2, 0)).unwrap();
        store.add("id:x".into(), hl("d", 3, 0)).unwrap();

        store.rename_book("lib:foo.epub", "lib:新书名.epub").unwrap();
        let mut ids: Vec<String> = store
            .list("lib:新书名.epub")
            .iter()
            .map(|h| h.id.clone())
            .collect();
        ids.sort();
        assert_eq!(ids, ["a", "b"], "alias records merged under the new key");
        assert!(store.list("lib:foo.epub").is_empty());
        assert!(store.list("lib:foo-2.epub").is_empty());
        assert_eq!(store.list("lib:bar.epub").len(), 1);
        assert_eq!(store.list("id:x").len(), 1);

        // Missing key → no-op.
        store.rename_book("lib:missing.epub", "lib:new.epub").unwrap();
        // Non-lib keys untouched (callers should skip them anyway).
        store.rename_book("id:x", "id:y").unwrap();
        assert!(store.list("id:x").len() == 1);
    }

    #[test]
    fn remove_book_leaves_other_ids_alone() {
        let mut store = AnnotationStore::in_memory();
        store.add("id:a".into(), hl("1", 0, 0)).unwrap();
        store.add("id:b".into(), hl("2", 0, 0)).unwrap();
        assert!(store.remove_book("id:a").unwrap());
        assert!(store.list("id:a").is_empty());
        assert_eq!(store.list("id:b").len(), 1);
    }

    #[test]
    fn books_are_isolated_and_ordered() {
        let mut store = AnnotationStore::in_memory();
        store.add("lib:one.epub".into(), hl("1", 0, 0)).unwrap();
        store.add("lib:one.epub".into(), hl("2", 1, 0)).unwrap();
        store.add("id:two".into(), hl("3", 5, 0)).unwrap();

        let one = store.list("lib:one.epub");
        assert_eq!(
            one.iter().map(|h| h.id.as_str()).collect::<Vec<_>>(),
            ["1", "2"]
        );
        assert_eq!(store.list("id:two").len(), 1);
        assert!(store.list("lib:missing.epub").is_empty());
    }

    #[test]
    fn same_id_replaces_without_duplicating() {
        let mut store = AnnotationStore::in_memory();
        store.add("k".into(), hl("a", 0, 0)).unwrap();
        let mut replaced = hl("a", 9, 9);
        replaced.text = "新摘录".into();
        store.add("k".into(), replaced).unwrap();
        let list = store.list("k");
        assert_eq!(list.len(), 1);
        assert_eq!(list[0].text, "新摘录");
    }

    #[test]
    fn corrupt_file_falls_back_to_empty() {
        let dir = std::env::temp_dir().join("icedreader-annotations-corrupt");
        let _ = fs::create_dir_all(&dir);
        let path = dir.join("annotations.json");
        fs::write(&path, b"not json {").unwrap();
        let store = AnnotationStore::open(path).unwrap();
        assert!(store.list("k").is_empty());
    }

    #[test]
    fn persist_only_writes_file_when_bound() {
        let mut store = AnnotationStore::in_memory();
        store.add("k".into(), hl("a", 0, 0)).unwrap();
        store.remove("k", "a").unwrap();
        let _ = store.add("k".into(), hl("b", 0, 0));
    }

    #[test]
    fn legacy_records_without_color_or_pos_read_with_defaults() {
        // Old annotations.json rows (pre colour/pos) must deserialise to
        // yellow at position 0 rather than failing the whole store.
        let json = r#"{
  "lib:old.epub": [
    {
      "id": "legacy-1",
      "href": "/EPUB/ch2.xhtml",
      "startText": 0,
      "startOffset": 0,
      "endText": 0,
      "endOffset": 5,
      "text": "旧摘录",
      "createdAt": 123
    }
  ]
}"#;
        let by_book: HashMap<String, Vec<Highlight>> = serde_json::from_str(json).unwrap();
        let list = by_book.get("lib:old.epub").unwrap();
        assert_eq!(list.len(), 1);
        assert_eq!(list[0].color, COLOR_YELLOW);
        assert_eq!(list[0].pos, 0.0);
    }

    #[test]
    fn color_and_pos_roundtrip_on_disk() {
        let dir = std::env::temp_dir().join("icedreader-annotations-color");
        let _ = fs::create_dir_all(&dir);
        let path = dir.join("annotations.json");
        let _ = fs::remove_file(&path);

        let mut store = AnnotationStore::open(path.clone()).unwrap();
        let mut h = hl("a", 1, 2);
        h.color = COLOR_GREEN.into();
        h.pos = 0.618;
        store.add("k".into(), h.clone()).unwrap();

        let reloaded = AnnotationStore::open(path).unwrap();
        let got = &reloaded.list("k")[0];
        assert_eq!(got.color, COLOR_GREEN);
        assert_eq!(got.pos, 0.618);
        assert_eq!(got.created_at, h.created_at);
    }
}
